# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/Users/ekremkose/RiderProjects/EShopModularMonolith/src"
      dockerfile: "Bootstrapper/Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "/Users/ekremkose/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/ekremkose/RiderProjects/EShopModularMonolith/src/Bootstrapper/Api:/app:rw"
    - "/Users/ekremkose/RiderProjects/EShopModularMonolith/src:/src:rw"
    working_dir: "/app"
